version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - db_data:/data
    environment:
      - DB_PATH=/data/score.db

  frontend:
    build: ./frontend
    ports:
      - "7777:80"
    environment:
      - REACT_APP_API_BASE=http://localhost:3001

volumes:
  db_data:
