FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py ./

ENV FLASK_APP=app.py
ENV DB_PATH=/data/score.db

EXPOSE 3001

CMD ["python", "app.py"]
